### ISSUE TITLE
No Issue : VZ200 query

### ISSUE THREAD

**Issue by bushy555** [toptensoftware/tapetool#1]
Hi,

What an intriguing awesome sounding bit of software.
Just a "throwing-it-out-there" query: Just wondering how hard it would be to also include the VZ200/VZ300 with its 600 baud cassette?   Taken from the VZ Tech manual:     bits 1 and 2 are used to generate th ecassette recording signal, which is about 200 millivolts peak-to-peak.

cheers

**Comment by toptensoftware** [comment]
It could probably be adapted but I don't have enough understanding of the VZ format (nor the time right now) to do the work.
